# Generated by Django 3.0.5 on 2020-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adult',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
