# Generated by Django 3.0.7 on 2020-06-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='a',
        ),
    ]
