# Generated by Django 3.0.5 on 2020-05-04 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200502_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
