# Generated by Django 3.0.5 on 2020-05-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_auto_20200505_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
