# Generated by Django 3.0.5 on 2020-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_auto_20200505_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='Enter', max_length=100),
        ),
    ]
